### ISSUE TITLE
P.201 最下段

### ISSUE THREAD

**Issue by indare** [agile-samurai-ja/support#27]
【もしバグ追跡システムをつかうことができないとしたら】
の最下段に
「考えるとこそ」
は
「考えることこそ」の間違い？

**Comment by hisashim** [comment]
第11-12刷では手違いで反映できておりませんでしたが（すみません）、
第13刷で反映させていただきます。

**Comment by hisashim** [comment]
遅くなりましたが、第13刷に反映されているはずです。
ありがとうございます。
closeします。
