### ISSUE TITLE
p. 245, 「～だろうのか」→「～だろうか」

### ISSUE THREAD

**Issue by hisashim** [agile-samurai-ja/support#31]
第8刷, p. 245, 「～だろうのか」

typoかなと思います。
変更案:

``` patch
-万が一省いたらどうなってしまうのだろうのか？
+万が一省いたらどうなってしまうのだろうか？
```

私の同僚のKSさんの指摘です。

**Comment by kakutani** [comment]
It will be fixed in 13rd print? 📚  @hisashim

**Comment by hisashim** [comment]
遅くなりましたが、第13刷に反映されているはずです。
ありがとうございます。
closeします。
