### ISSUE TITLE
p.34 自分はどうやって貢献するつもりか?

### ISSUE THREAD

**Issue by nawoto** [agile-samurai-ja/support#32]
第8刷 p.34 22,26行目
レビューアの角さんからの指摘。原文が「How do I perform?」だから、ニュアンスが違うそうです。修正案は以下だそうです。

変更案:

``` patch
-自分はどうやって貢献するつもりか?
+自分はどういうふうに仕事するか？
-どうやって貢献するつもりで
+どういうふうに仕事するか
```

**Comment by kakutani** [comment]
13刷に反映おねがいします 📈   @hisashim

**Comment by hisashim** [comment]
助詞の「を」を省いて「仕事する」とするのがよいですか？

個人的には「仕事をする」のほうがしっくり来ますが、語感やくだけた雰囲気を出す上で
「仕事する」のほうが適当ならば、そうしましょう。

**Comment by kakutani** [comment]
ドラッカー・エクササイズは簡易なワークショップなので、口語っぽいほうがいいかなーと思ったのですが、「しごとをする」は発話するので、

> 助詞の「を」を省いて「仕事する」とするのがよいですか？

省かずに「仕事をする」でお願いします!

**Comment by hisashim** [comment]
分かりました。ではそのように。

なお2段落後に

>  What results can you expect me to deliver?
> チームメンバーは自分にどんな成果を期待してると思うか？

とありますが、こちらの「期待してる」は「期待している」とせずにママでよいですか。
口語ならありかなと思いますし、ご指示がなければママとします。

**Comment by kakutani** [comment]
言われてみると気になってきたのですが、致命的ではないのでﾏﾏでおねがいします 👒

**Comment by hisashim** [comment]
第13刷で次のように変更します。

p. 34, ll. 22, 26:
```diff
-自分はどうやって貢献するつもりか？
+自分はどういうふうに仕事をするか？

-チームメンバー同士でこの質問に答えてみよう。[...]どうやって貢献するつもりで、[...]
+チームメンバー同士でこの質問に答えてみよう。[...]どういうふうに仕事をするか、[...]
```

**Comment by hisashim** [comment]
遅くなりましたが、第13刷に反映されているはずです。
ありがとうございます。
closeします。
