### ISSUE TITLE
p.223 グラフのタイトル　「バーダウンチャート」→「バーンダウンチャート」（第1版第4刷）

### ISSUE THREAD

**Issue by taroyabuki** [agile-samurai-ja/support#35]
誤：バーダウンチャート
正：バーンダウンチャート

**Comment by hisashim** [comment]
@taroyabuki ご指摘ありがとうございます。
第13刷にも存在するのを確認しました。
近日予定の第14刷で修正されるよう手配します。

* p. 223, ページ下端の、チームのベロシティとプロジェクトのバーンダウンチャートを
  示した図中のテキスト

  - 変更前: 「プロジェクトのバーダウンチャート」
  - 変更後: 「プロジェクトのバーンダウンチャート」

**Comment by hisashim** [comment]
2017-06-20発行予定の第14刷で修正されるよう、手配しました。
どうもありがとうございます。
