### ISSUE TITLE
p.34 ドラッカー風エクササイズ4問目

### ISSUE THREAD

**Issue by kdmsnr** [agile-samurai-ja/support#36]
```diff
- チームメンバーは自分にどんな成果を期待していると思うか？
+ チームメンバーは自分にどんな成果を期待できるか？
```
表現がまわりくどいので、元の2問目みたいな「自分はどうやって貢献できるか」でもよさそう。

**Comment by hisashim** [comment]
@kdmsnr ご提案ありがとうございます。ご報告がたいへん遅くなってしまいました。
第16刷で取り込ませていただく予定とのことです。

  * p.34, 囲み記事内の箇条書きの4番目の項目
    - 変更前
      > チームメンバーは自分にどんな成果を期待してると思うか？
    - 変更後
      > チームメンバーは自分にどんな成果を期待できるか？

今後とも、どうぞよろしくお願いいたします。
